{{- if not .Values.secrets.existingSecret }}
{{- if .Values.externalSecret.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "hivemind.fullname" . }}-secrets
  labels:
    {{- include "hivemind.labels" . | nindent 4 }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: {{ .Values.externalSecret.secretStoreRef.name }}
    kind: {{ .Values.externalSecret.secretStoreRef.kind }}
  target:
    name: {{ include "hivemind.fullname" . }}-secrets
  dataFrom:
    - find:
        path: {{ .Values.externalSecret.remoteKeyPrefix }}
{{- else }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "hivemind.fullname" . }}-secrets
  labels:
    {{- include "hivemind.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- range $k, $v := .Values.secrets.data }}
  {{- if $v }}
  {{ $k }}: {{ $v | quote }}
  {{- end }}
  {{- end }}
{{- end }}
{{- end }}
