# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from hivemind.executor.proto import executor_pb2 as hivemind_dot_executor_dot_proto_dot_executor__pb2

GRPC_GENERATED_VERSION = '1.81.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in hivemind/executor/proto/executor_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class CodeExecutorStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Execute = channel.unary_unary(
                '/hivemind.executor.v1.CodeExecutor/Execute',
                request_serializer=hivemind_dot_executor_dot_proto_dot_executor__pb2.ExecuteRequest.SerializeToString,
                response_deserializer=hivemind_dot_executor_dot_proto_dot_executor__pb2.ExecuteResponse.FromString,
                _registered_method=True)


class CodeExecutorServicer:
    """Missing associated documentation comment in .proto file."""

    def Execute(self, request, context):
        """Run code to completion and return the aggregated result (unary, matching SandboxResult).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CodeExecutorServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Execute': grpc.unary_unary_rpc_method_handler(
                    servicer.Execute,
                    request_deserializer=hivemind_dot_executor_dot_proto_dot_executor__pb2.ExecuteRequest.FromString,
                    response_serializer=hivemind_dot_executor_dot_proto_dot_executor__pb2.ExecuteResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'hivemind.executor.v1.CodeExecutor', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('hivemind.executor.v1.CodeExecutor', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class CodeExecutor:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Execute(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hivemind.executor.v1.CodeExecutor/Execute',
            hivemind_dot_executor_dot_proto_dot_executor__pb2.ExecuteRequest.SerializeToString,
            hivemind_dot_executor_dot_proto_dot_executor__pb2.ExecuteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
