# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: hivemind/executor/proto/executor.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'hivemind/executor/proto/executor.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n&hivemind/executor/proto/executor.proto\x12\x14hivemind.executor.v1\"G\n\x0e\x45xecuteRequest\x12\x0c\n\x04\x63ode\x18\x01 \x01(\t\x12\x14\n\x0c\x61rtifact_dir\x18\x02 \x01(\t\x12\x11\n\ttimeout_s\x18\x03 \x01(\x05\"W\n\x0f\x45xecuteResponse\x12\x11\n\texit_code\x18\x01 \x01(\x05\x12\x0e\n\x06stdout\x18\x02 \x01(\t\x12\x0e\n\x06stderr\x18\x03 \x01(\t\x12\x11\n\ttimed_out\x18\x04 \x01(\x08\x32\x66\n\x0c\x43odeExecutor\x12V\n\x07\x45xecute\x12$.hivemind.executor.v1.ExecuteRequest\x1a%.hivemind.executor.v1.ExecuteResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'hivemind.executor.proto.executor_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EXECUTEREQUEST']._serialized_start=64
  _globals['_EXECUTEREQUEST']._serialized_end=135
  _globals['_EXECUTERESPONSE']._serialized_start=137
  _globals['_EXECUTERESPONSE']._serialized_end=224
  _globals['_CODEEXECUTOR']._serialized_start=226
  _globals['_CODEEXECUTOR']._serialized_end=328
# @@protoc_insertion_point(module_scope)
